services:
  - type: web
    name: taskmanager
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn taskmanager.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanager_db
          property: connectionString

databases:
  - name: taskmanager_db
    databaseName: taskmanager
    user: taskmanager